### ISSUE TITLE
subnets for ELB should be either internet facing (as well as the masters), or internal (as well as the masters)

### ISSUE THREAD

**Issue by jaykeshur** [UKHomeOffice/keto#54]
Currently the ELB is internet facing. but the masters are attached to a route table going through an nat gateway.

**Comment by vaijab** [comment]
We decided to add a new flag `--private=true` or `--internal=true` that will make a cluster nodes without public IPs and with internal ELB.

**Comment by vaijab** [comment]
Done by #72
