### ISSUE TITLE
Internal cluster

### ISSUE THREAD

**Issue by vaijab** [UKHomeOffice/keto#71]
Related #54 

We need to support internal clusters as well as external (default). This is an attempt to define what and how an internal cluster look like.

### What is an internal cluster
This is cloud provider dependant, but let's focus on AWS for now. An internal cluster is one with:
- ASGs without public IPs, behind a NAT
- Internal kube API ELB

### Internal cluster pre-prerequisite (not managed by keto)
- Properly configured subnets and a NAT gateway
- Access to internal VPC networks, can be done via VPN or a bastion host

### Questions
- Should `--internal=true` flag only be available during `keto create cluster --internal=true`?
  - Yes. Additional pools or pools that are recreated will be automatically made as internal.
- Will we ever need to create an external compute pool for internal cluster?
  - No, at this point. We'll review this once we have a use case or when we implement other clouds.

**Comment by KashifSaadat** [comment]
Would the Platform Hub fall under the requirement of being hosted within an internal cluster and having an external compute pool (open endpoint allowing users to download a VPN profile)?

**Comment by lewismarshall** [comment]
As `--internal' only applicable to cluster creation (As the ELB is created during CreateClusterInfra), without much more work, this is fine until we have to support anything else.

Not sure about an external compute pool. Seems like a risk and again not required. Trying to think through ingress @gambol99

**Comment by vaijab** [comment]
> Would the Platform Hub fall under the requirement of being hosted within an internal cluster and having an external compute pool

Applications hosted within a cluster will be able to be accessed via an ingress ELB that is separate from kube API ELB, so no need to take apps into consideration.

**Comment by vaijab** [comment]
> Not sure about an external compute pool. Seems like a risk and again not required.

I am with you on this. I cannot think of any reason to have a compute pool with public IPs if the rest of the cluster is internal.

**Comment by rsuniev** [comment]
Shall we just have "kube_elb_internal" flag as from dsp 1.0 then instead of "--internal=true"?

**Comment by vaijab** [comment]
> Shall we just have "kube_elb_internal" flag

Probably not. Internal cluster is not just about its ELB, also ELB is AWS specific. We should keep keto as cloud agnostic as possible.

**Comment by karnauskas** [comment]
Are you considering ipv6 support? If so, how internal/external would be defined on ipv6 address space?

**Comment by vaijab** [comment]
> Are you considering ipv6 support?

No IPv6 yet, but would be interesting to see it working!

**Comment by vaijab** [comment]
Done by #72
